<?php
/**
 * @var $activeCompany \Lib3rdParty\Authentication\SystemOwnerInterface
 */

$jsCssData = $this->getHelperPluginManager()->getServiceLocator()->get('AuthV2\\JsCssData');
#echo '<pre>'.htmlentities(print_r($jsCssData, true)).'</pre>';
if(array_key_exists('css', $jsCssData) && array_key_exists('files', $jsCssData['css'])){
    foreach($jsCssData['css']['files'] as $cssFile) $this->headLink()->prependStylesheet($cssFile);
}
if(array_key_exists('js', $jsCssData) && array_key_exists('files', $jsCssData['js'])){
    foreach($jsCssData['js']['files'] as $jsFile) $this->headScript()->prependFile($jsFile);
}
/**
Array
(
    [js] => Array
        (
            [files] => Array
                (
                    [0] => login.js
                )
            [code] => ''
        )

    [css] => Array
        (
            [files] => Array
                (
                    [0] => login.css
                )
            [code] => ''
        )
)
 */

$queryParams = $this->getHelperPluginManager()->getServiceLocator()->get('request')->getUri()->getQueryAsArray();
$title = 'Sign In';
if(array_key_exists('redirect', $queryParams) && $queryParams['redirect'] == 'checkout'){
    $title .= ' or Create Account';
}
$this->headTitle($title);
#if(!empty($error)) echo '<pre>'.$error.'</pre>';
#if($isFormSubmitted && !$isPasswordOK) echo '<h3>Incorrect login information</h3>';
/*
 $form = $this->form;
 $form->setAttribute('action', $this->url('login'));
 $form->prepare();
 echo $this->form()->openTag($form);
 #echo '<div class="form-group">'.$this->formRow($form->get('loginId')).'</div>';
 #echo '<div class="form-group">'.$this->formRow($form->get('loginPass')).'</div>';
 echo $this->formCollection($form);
 #echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
*/
#echo '<h3>whoAmI: '.$this->whoAmI.'</h3>';
/*
*/
$this->headLink()->offsetSetStylesheet(101, $this->basePath().'/css/login.css');
$loginForm=$this->plugin('loginForm'); ?>
<div class="wms-form-control accountlogingeneral">
    <div class="creant-new-account">
        <h1>Welcome<?php
        if(isset($activeCompany) && is_object($activeCompany)) echo ' to '.$activeCompany->getName(); ?></h1>
        <?php if(isset($registrationUrl)): ?>
        <?php if(array_key_exists('redirect', $queryParams) && $queryParams['redirect'] == 'checkout'){ ?>
            <span class="creant-new-account-title"><?php echo $title; ?></span>
        <?php } else{ ?>
            <span class="creant-new-account-title-left"><?php echo $title; ?></span>
        <?php } ?>
        <?php endif; ?>
    </div>
    <div class="left-block">
        <?php echo (!empty($error)?'<div class="required-field-error-message">'.$error.'</div>':''); ?>
        <!--<div class="welcome-info">
            <span class="rtcustomer">Returning Customer</span><br>
            <span class="welcome-message"> Welcome Back! Please enter your email address and password below. </span>
        </div>-->
        <div class="custom-table account-login">
            <div class="tr">
                <div class="heading2 td">
                    <!-- login form --> <?=$loginForm()?> <?=(true==$anonymousLoginEnabled?'<a href="'.$this->url('login', array('action'=>'anonymous-login')).'">Proceed as Guest</a> '.(isset($forgotPasswordUrl)?'| ':''):'')?>
                    <?php echo (isset($forgotPasswordUrl)?'<font><a class="underlinetext" href="'.$forgotPasswordUrl.'">Reset Your Password?</a></font>':''); ?>
                    <?php
                    /*if(isset($registrationUrl)):
                        echo (true==$anonymousLoginEnabled?'<br /><br /><span class="underlinetext">Or, click here to</span><br />':'');
                    endif;
                    if(!array_key_exists('redirect', $queryParams) || (array_key_exists('redirect', $queryParams) && $queryParams['redirect'] != 'checkout')){
                        echo (isset($forgotPasswordUrl)?' | ':''); ?>
                        <a href="<?php echo $registrationUrl;?>" class="underlinetext"><b>CREATE NEW ACCOUNT</b></a>
                    <?php }*/ ?>
                </div>
            </div>
        </div>
    </div>
    <div class="right-block">
        <?php //if(array_key_exists('redirect', $queryParams) && $queryParams['redirect'] == 'checkout'){ ?>
        <?php if(isset($registrationUrl)): ?>
        <span class="rtcustomer">New User?</span><br />
        <span class="welcome-message"> Hello</span><br />
        <a class="btn btn-bg btn-account-bg" href="<?php echo $registrationUrl; ?>" class="underlinetext"><b>Create Your Account</b></a>
        <?php endif; ?>
        <?php //}else{ ?>
        <!--<div class="login-description">
                <div class="accountlogin">Account Login</div>
                <div class="details">
                    <?php /*if(isset($forgotPasswordUrl)): */?>
                        <span class="accountlogintitle">Reset Your Password?</span><br>
                        Click <a href="<?php /*echo $forgotPasswordUrl; */?>" class="underlinetext">here</a>
                        and simply enter your email address. If the email is registered,
                        we'll send the password to that email address.
                    <?php /*endif; */?>
                    <span class="accountlogintitle">The website isn't accepting my
				password,<br> now what?
			</span><br> The password is case sensitive. Please verify that the
                    CAPS LOCK key on your keyboard is not activated.
                </div>
            </div>-->
        <?php //} ?>
    </div>
</div>
<?php
/* $this->headStyle()->captureStart();
echo $loginForm->getCss();
$this->headStyle()->captureEnd(); */