<?php
$url=$this->plugin('url');
$title = 'Wurfl Detect Information';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 
$wurflHelper=$this->plugin('wurfl');
$wurflInfo = $wurflHelper->getWURFLInfo();
$qryParams=$this->getHelperPluginManager()->getServiceLocator()->get('request')->getUri()->getQueryAsArray();
if (array_key_exists('ua', $qryParams)) {
	$ua=$qryParams['ua'];
	$requestingDevice = $wurflHelper->getDeviceForUserAgent($qryParams['ua']);
} else {
	$ua = $_SERVER['HTTP_USER_AGENT'];
	$requestingDevice = $wurflHelper->getRequestingDevice();
}
?>
	<h3>WURFL XML INFO</h3>
	<ul>
	    <li><h4>VERSION: <?php echo $wurflInfo->version; ?> </h4></li>
	</ul>
	<div id="content">
		User Agent: <b> <?php echo htmlspecialchars($ua); ?> </b>
		<ul>
			<li>ID: <?php echo $requestingDevice->id; ?> </li>
			<li>Brand Name: <?php echo $requestingDevice->getCapability('brand_name'); ?> </li>
			<li>Model Name: <?php echo $requestingDevice->getCapability('model_name'); ?> </li>
			<li>Marketing Name: <?php echo $requestingDevice->getCapability('marketing_name'); ?> </li>
			<li>Preferred Markup: <?php echo $requestingDevice->getCapability('preferred_markup'); ?> </li>
			<li>Resolution Width: <?php echo $wurflHelper->getResolutionWidth('resolution_width'); ?> </li>
			<li>Resolution Height: <?php echo $requestingDevice->getCapability('resolution_height'); ?> </li>
		</ul>
		<p><b>Query WURFL by providing the user agent:</b></p>
		<form method="get" action="<?php echo $url('wurfl'); ?>">
			<div>User Agent: <input type="text" name="ua" size="100" value="<?php echo isset($_GET['ua'])? htmlspecialchars($_GET['ua']): ''; ?>" />
			<input type="submit" /></div>
		</form>
	</div>

